triggers:
  - triggers.yfinance_kafka_trigger.KafkaEventListener

schedulers:
  - schedulers.hourly.HourlyScheduler

operators:
  - transformers.my_operators.PostgresWriter
  - transformers.my_operators.MinioReader
  - transformers.my_operators.AggregatePrices
